### ISSUE TITLE
Warning message about enumerable-statistics on MacOS 15.0

### ISSUE THREAD

**Issue by JeromeLefebvre** [red-data-tools/YouPlot#53]
Since upgrading to MacOS 15.0, I receive the following message each time I call uplot.

```
 % uplot
Ignoring enumerable-statistics-2.0.8 because its extensions are not built. Try: gem pristine enumerable-statistics --version 2.0.8

Program: YouPlot (Tools for plotting on the terminal)
Version: 0.4.6 (using UnicodePlot 0.0.5)
Source:  https://github.com/red-data-tools/YouPlot
```
I have not noticed any issues with the functionality, but I only use uplot to trend line graphs.

**Comment by kou** [comment]
Could you try running `gem pristine enumerable-statistics --version 2.0.8` as the message said?

**Comment by kojix2** [comment]
Hello JeromeLefebvre,

Thank you for trying YouPlot.  
In my experience, when macOS is updated, command-line tools often stop working. This is probably because macOS changes the ABI of some libraries, which causes problems with software that uses dynamic linking.

`enumerable-statistics` is a C extension that compiles a shared library. This library is linked to `libruby`.

```
otool -L lib/enumerable/statistics/extension.bundle
	/Users/runner/hostedtoolcache/Ruby/3.3.5/arm64/lib/libruby.3.3.dylib (compatibility version 3.3.0, current version 3.3.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1345.120.2)
```

It is likely that one of the libraries that `libruby` depends on has changed its ABI, which is why the link is failing. To fix this, you might need to reinstall Ruby, and if that does not work, you can try running `brew list | xargs brew reinstall`. There are often problems with `libssl` in particular.

This problem is not directly related to YouPlot, but I also often face similar issues and understand how frustrating it can be.  
Thank you for your report.

**Comment by JeromeLefebvre** [comment]
Thank you for the detailed explanation.
In my environment, gem, irb, ruby commands are those comming directly from MacOS and now home-brew.

Reinstalling only uplot ```brew reinstall youplot``` resolved the error.
